aliBuild prerequisite for Ubuntu - Need "graphviz" (#145)
For Ubuntu (at least my Kubuntu 20.04 LTS), I do not succeed to use "alibuild deps" to create graphs dependencies since quite some time.

6 amaire-sbgat92: AliceSuite >aliBuild deps YODA --defaults generators --outgraph test.pdf
ERROR: Error generating dependencies with dot: FileNotFoundError: [Errno 2] No such file or directory: 'dot'

I have just figured out that my system miss a needed system package : graphviz

Co-authored-by: Giulio Eulisse <10544+ktf@users.noreply.github.com>