aliBuild prerequisite - Need package python3-pydot
For Ubuntu (at least my Kubuntu 20.04 LTS), I do not succeed to use "alibuild deps" to create graphs dependencies since quite some time.

6 amaire-sbgat92: AliceSuite >aliBuild deps YODA --defaults generators --outgraph test.pdf
ERROR: Error generating dependencies with dot: FileNotFoundError: [Errno 2] No such file or directory: 'dot'

I have just figured out that my system miss a needed system package : python3-pydot
I updated here the apt install command to include such an extra package